// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: testdata/timed.proto

package testdata

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/opsee/protobuf/opseeproto"
	types "github.com/opsee/protobuf/opseeproto/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Timed struct {
	UpdatedAt            *types.Timestamp `protobuf:"bytes,1,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Timed) Reset()         { *m = Timed{} }
func (m *Timed) String() string { return proto.CompactTextString(m) }
func (*Timed) ProtoMessage()    {}
func (*Timed) Descriptor() ([]byte, []int) {
	return fileDescriptor_a878f7fd3e65d769, []int{0}
}
func (m *Timed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timed.Unmarshal(m, b)
}
func (m *Timed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timed.Marshal(b, m, deterministic)
}
func (m *Timed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timed.Merge(m, src)
}
func (m *Timed) XXX_Size() int {
	return xxx_messageInfo_Timed.Size(m)
}
func (m *Timed) XXX_DiscardUnknown() {
	xxx_messageInfo_Timed.DiscardUnknown(m)
}

var xxx_messageInfo_Timed proto.InternalMessageInfo

func (m *Timed) GetUpdatedAt() *types.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Timed)(nil), "testdata.Timed")
}

func init() { proto.RegisterFile("testdata/timed.proto", fileDescriptor_a878f7fd3e65d769) }

var fileDescriptor_a878f7fd3e65d769 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x49, 0x2d, 0x2e,
	0x49, 0x49, 0x2c, 0x49, 0xd4, 0x2f, 0xc9, 0xcc, 0x4d, 0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x80, 0x89, 0x4a, 0x19, 0xa4, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7,
	0xea, 0xe7, 0x17, 0x14, 0xa7, 0xa6, 0xea, 0x83, 0x55, 0x24, 0x95, 0xa6, 0x41, 0xb8, 0x60, 0x1e,
	0x84, 0x09, 0xd1, 0x2b, 0x65, 0x45, 0x94, 0x8e, 0x92, 0xca, 0x82, 0xd4, 0x62, 0xb0, 0x9d, 0xc5,
	0x25, 0x89, 0xb9, 0x05, 0x10, 0xbd, 0x4a, 0x76, 0x5c, 0xac, 0x21, 0x20, 0x67, 0x08, 0x99, 0x72,
	0x71, 0x95, 0x16, 0xa4, 0x24, 0x96, 0xa4, 0xa6, 0xc4, 0x27, 0x96, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x1b, 0x89, 0xe9, 0x41, 0xac, 0x01, 0x6b, 0xd5, 0x0b, 0x81, 0x69, 0x0d, 0xe2, 0x84, 0xaa,
	0x74, 0x2c, 0x71, 0x62, 0x39, 0xb0, 0x48, 0x9e, 0x31, 0x89, 0x0d, 0x6c, 0x98, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x20, 0xcd, 0x26, 0xb2, 0xdc, 0x00, 0x00, 0x00,
}
